DROP TABLE IF EXISTS PrinterUsage;
DROP TABLE IF EXISTS Printer;
DROP TABLE IF EXISTS RoomReserved;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS BookLocator;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS Users;
