DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS RoomReservation;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS BookLocator;
DROP TABLE IF EXISTS Printer;
DROP TABLE IF EXISTS PrinterUsage;
DROP TABLE IF EXISTS FeedbackForms

--DROP TABLE IF EXISTS RoomReserved;
